<?php


function contactform_theme($existing, $type, $theme, $path)
{
    return array( 'contact_site_form' => array(	'template' => 'contact-site-form',
												'path'	=> drupal_get_path('module', 'contactform').'/inc',
												'render element' => 'form',
  										 	),
    	  		);
}

function contactform_form_alter(&$form, &$form_state, $form_id)
{
	if($form_id == 'contact_site_form'){
		$form['actions']['submit']['#value'] = 'Send your message';
		$form['name']['#attributes'] = array('placeholder'	=> 'Name *');
		$form['mail']['#attributes'] = array('placeholder'	=> 'Email *');
		$form['subject']['#attributes'] = array('placeholder'	=> 'Subject *');
		$form['actions']['submit']['#attributes'] = array('id'	=> 'edit-submit');
	}
}

function contactform_preprocess_contact_site_form(&$variables) 
{
	$form = $variables['form'];
	
	unset($form['name']['#title']);
	unset($form['mail']['#title']);
	unset($form['subject']['#title']);
	unset($form['message']['#title']);
	
	$variables['form'] = $form;

}

function contactform_preprocess_page(&$variables)
{
	if($variables['is_front']){
		require_once( drupal_get_path('module', 'contact').'/contact.pages.inc');
		$contact = drupal_get_form('contact_site_form');
		$variables['custom_contact_form'] = drupal_render($contact);
	}
}