<?php

function baseproject_preprocess_page(&$variables)
{
	if($variables['site_name']){
		$names = explode(' ', $variables['site_name']);
		
		// removes the first word of the site name
		//and assign it to a site_name1 variable
		$variables['site_name1'] = array_shift($names); 
		
		// merges the remaining array items to a single string
		//and assigns it to a site_name2 variable
		$variables['site_name2'] = implode(' ', $names);
	}
}

